### ISSUE TITLE
Provide testing info

### ISSUE THREAD

**Issue by jaygrieves** [s2shape/AzureCosmosSupplyCollector#1]
Please update the README with how to test this collector, ideally with a run-tests.sh script.  Use the emulator Docker if possible: https://hub.docker.com/r/microsoft/azure-cosmosdb-emulator/

**Comment by burilovmv** [comment]
Unfortunately, azure-cosmosdb-emulator can run only on Windows host, so can't use it for tests.

**Comment by burilovmv** [comment]
Added testing info for the actual cloud
